### PR TITLE
Do not cache the result of CreateService

### PR DESCRIPTION
**Pull request by tomchop**
Calls to `GoogleCloudFunction` would otherwise retain stale credentials if the object was reused to call `ExecuteFunction` over long periods of time

### CODE REVIEW

**Review by giovannt0 — COMMENTED** [review]
If we're not gonna cache it, shouldn't we remove the `self.xxxx` attributes all-together and just directly return the result of the call to the service builder?

**Comment by tomchop** [comment]
One could argue that it makes it easier to debug to have an intermediary variable, but I agree that we can remove it altogether.

**Comment by giovannt0** [comment]
Yeah, I don't have a strong preference here, so I'll approve this and let you decide

**Review by giovannt0 — APPROVED** [review]

**Comment by giovannt0** [comment]
(Pending build success)

**Comment by tomchop** [comment]
Force merging this as we want these changes in sooner rather than later.

**Pull request merged**
