### PR TITLE
Fix deleteinstance command line function

### LINKED ISSUE #273: GCP deleteinstance not working
Version: 20201124.1

To reproduce
`cloudforensics gcp <project id> deleteinstance --delete_all_disks <instance name to delete>`

Error Message:
```
Traceback (most recent call last):
  File "/usr/local/bin/cloudforensics", line 10, in <module>
    sys.exit(Main())
  File "/Library/Python/3.8/site-packages/tools/cli.py", line 367, in Main
    parsed_args.func(parsed_args)
  File "/Library/Python/3.8/site-packages/tools/gcp_cli.py", line 98, in DeleteInstance
    instance.Delete(delete_disks=args.delete_disks)
AttributeError: 'Namespace' object has no attribute 'delete_disks'
```

### PR DESCRIPTION
**Pull request by giovannt0**
Fix #273 

- Fix attribute selection from argparser
- Fix `try/except` block catching the wrong exception. When `delete_all_disks` is `True`, the library will try to delete the disk that has already been deleted by the `instance delete` operation, thus throwing a `ResourceNotFoundError` error.

```
~/(venv) giovannt0@: cloudforensics gcp <project_id> deleteinstance instance-1 --delete_all_disks
[2020-12-17 14:31:25,239] [libcloudforensics.providers.gcp.internal.compute] INFO     project:<project_id> Deleting Instance: instance-1
[2020-12-17 14:31:43,852] [libcloudforensics.providers.gcp.internal.compute] ERROR    Disk instance-1 was not found in project <project_id>
[2020-12-17 14:31:43,852] [libcloudforensics.providers.gcp.internal.compute] INFO     project:<project_id> Could not find disk: instance-1, skipping
Instance deleted.
```

Despite the logging, the instance and its disk are now deleted as expected. Alternatively we could filter out already deleted disks from the `disks_to_delete` list to prevent `ResourceNotFoundError` from being thrown in the first place.

### CODE REVIEW

**Comment by giovannt0** [comment]
@googlebot I signed it!

**Review by hacktobeer — APPROVED** [review]

**Comment by hacktobeer** [comment]
And have a lovely Christmas/NYE Theo!

**Comment by giovannt0** [comment]
> And have a lovely Christmas/NYE Theo!

**Comment by giovannt0** [comment]
Thank you @hacktobeer, you as well!

**Review by sa3eed3ed — APPROVED** [review]
LGTM

**Pull request merged**
